blog/urls.py
from django.urls import path

from . import views
app_name = 'blog'
urlpatterns = [
     path('', views.home_page, name='home_page'),
]

my_site/urls.py
from django.urls import include, path 
from django.contrib import admin

urlpatterns = [ 
     path('', include('blog.urls')), 
     path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models

# Create your models here.
class Comment(models.Model):
     comment = models.CharField(max_length=180, null=True, blank=True)
     user = models.CharField(max_length=180, null=True, blank=True)

blog/views.py
from django.shortcuts import render
from . models import Comment 
# Create your views here.
def home_page(request):
    if request.method == 'POST' : 
        our_comment = request.POST.get('comment')
        our_user = request.POST.get("username")
        comment_obj = Comment.objects.create(
         comment = our_comment,
         user = our_user
         )


        
        return render(request, 'blog/home_page.html', {'comment': comment_obj,})

    return render(request, 'blog/home_page.html')
    

blog/templates/blog/home_page.html
<!DOCTYPE html>
<html>
<head>
 <title>Welcome to Yonnie's Blog</title>
</head>
<body>
 <!-- Site Header -->
 <h1>Hi. I am Yonnie. Welcome to my blog!</h1>

<!-- Blog Post -->
 <h2>My First Blog Post</h2>
 <p>Here is my first blog post. One day at the mall....</p>
<p><img style="width: 200px" src="https://static.independent.co.uk/s3fs-public/thumbnails/image/2014/02/08/20/p18codeREX.jpg"></p>



<!-- Like And Comment -->
 <button>Like</button>
 <h2>Leave a Comment</h2>
 <form action="{% url 'blog:home_page' %}" method="POST">
 {% csrf_token %}
 <input type="text" placeholder="Please Enter Your username" name="username"><br><br>
 <textarea name="comment" placeholder="Please Enter Your Comment"></textarea><br>
 <input type="submit" value="Post Me!">
 </form>

<h2>Comments</h2>
 User {{comment.user}} says: {{comment.comment}}
</body>
</html>